"""Agent-facing contracts — re-export the single source in terminal_agent.contracts."""

from __future__ import annotations

from terminal_agent.contracts import (
    AgentRole,
    Attribution,
    Budget,
    ChangeSource,
    CompiledTaskCandidate,
    Criterion,
    DeviceDomain,
    DeviceTask,
    ExecutionStatus,
    GoalOutcome,
    MutableModel,
    PendingInteraction,
    PlanDraft,
    PolicyDecision,
    ReviewDecision,
    ReviewResult,
    RouterDecision,
    RouteType,
    RunLifecycle,
    RunPhase,
    RunRecord,
    RuntimeEvent,
    StateSnapshot,
    TaskSpec,
    ToolAction,
    VerificationStatus,
    dict_of,
    new_id,
    now,
    utcnow,
)

__all__ = [
    "AgentRole",
    "Attribution",
    "Budget",
    "ChangeSource",
    "CompiledTaskCandidate",
    "Criterion",
    "DeviceDomain",
    "DeviceTask",
    "ExecutionStatus",
    "GoalOutcome",
    "MutableModel",
    "PendingInteraction",
    "PlanDraft",
    "PolicyDecision",
    "ReviewDecision",
    "ReviewResult",
    "RouteType",
    "RouterDecision",
    "RunLifecycle",
    "RunPhase",
    "RunRecord",
    "RuntimeEvent",
    "StateSnapshot",
    "TaskSpec",
    "ToolAction",
    "VerificationStatus",
    "dict_of",
    "new_id",
    "now",
    "utcnow",
]
